da_DK: remove .idx file
Otherwise, daily builds fail with
ERROR: ERROR: 'destination' at file not unique: LibreOfficeDev 27/share/extensions/dict-da/th_da_DK.idx at E:/jenkins/workspace/lo_daily_src/solenv/bin/modules/installer/windows/file.pm line 135.

Change-Id: Ie3685591867166a72a7734f564c3cf0f0e26679a
Reviewed-on: https://gerrit.libreoffice.org/c/dictionaries/+/206974
Reviewed-by: Xisco Fauli <xiscofauli@libreoffice.org>
Tested-by: Xisco Fauli <xiscofauli@libreoffice.org>
(cherry picked from commit cdaeab266e35c0f1ce367629c7f2079c64fe9351)
Reviewed-on: https://gerrit.libreoffice.org/c/dictionaries/+/206976